### ISSUE TITLE
Consult for Reddit bspwm Solarized Light theme

### ISSUE THREAD

**Issue by Ynjxsjmh** [Wallkerock/X-setup#1]
I really like your polybar theme in your reddit post [\[bspwm\]Solarized Light : unixporn](https://www.reddit.com/r/unixporn/comments/ccdawb/bspwmsolarized_light/), but I didn't find it in your README picture. Could you help point out where is it?

![image](https://user-images.githubusercontent.com/40143136/150684737-6131269b-575b-4adf-aad7-0739bf8b0b22.png)

**Comment by Wallkerock** [comment]
Sorry, but I can not remember. This is my older theme. On Github I have the
latest themes. All configs are there.

BSPWM - Solarized Light
<https://github.com/Wallkerock/X-setup/tree/master/.config/bspwm/Bspwm-Solarized-Light>
[image: bspwm-solarized-light-02.png]

BSPWM - Solarized Light Yellow
<https://github.com/Wallkerock/X-setup/tree/master/.config/bspwm/Bspwm-Solarized-Yellow>
[image: bspwm-solarized-light-yellow-01.png]

ne 23. 1. 2022 o 16:03 Winy Song ***@***.***> napísal(a):

**Comment by Ynjxsjmh** [comment]
Thanks for your reply, that's really a pity. Current Solarized Light looks a little cold and Solarized Light Yellow looks too deep. That older one looks just suitable to me, I will try to use color picker to pick the color and thanks for your sharing.
